### ISSUE TITLE
Working

### ISSUE THREAD

**Issue by dikokob** [richardeoin/ax#1]
Hi Richard,

Have you tested the operation of your code?

**Comment by richardeoin** [comment]
Hi Boitumelo,

Some modes have been tested, such as FSK (2000-20000 baud) and APRS.
However there is no systematic test coverage yet.

You can create an issue if there is a problem and I may fix it.

**Comment by dikokob** [comment]
Thanks for the follow up Richard,

Could I please send me your private email address.
